language: node_js
node_js:
  - "12.18.2"

dist: trusty
addons:
  chrome: stable
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3

services:
  - mongodb
  - redis

env:
  - NODE_ENV=ci PORT=3000

cache:
  directories:
    - node_modules
    - client/node_modules

before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - npm install
  - npm run build:client
  - npm run build:server

script:
  - nohup npm run start:prod &
  - sleep 3
  - npm run test
