language: node_js
node_js:
  - "12.18.2"

dist: trusty

services:
  - mongodb
  - redis

env:
  - NODE_ENV=ci PORT=3000

cache:
  directories:
    - node_modules
    - client/node_modules

install:
  - npm install
  - npm run build:client
  - npm run build:server

script:
  - nohup npm run start:prod &
  - sleep 3
  - npm run test
